#!/bin/sh
# Render dnsmasq config from environment, then run it.
#
# Modes:
#   MODE=proxy  -> proxyDHCP: coexists with an existing DHCP server (default)
#   MODE=dhcp   -> standalone DHCP: this server also hands out IP leases
set -eu

MODE="${MODE:-dhcp}"
TFTP_ROOT="/srv/tftp"
CONF="/etc/dnsmasq.runtime.conf"
: "${SERVER_IP:?Set SERVER_IP to the provisioning server IP address}"
# Required, not optional. This container runs with host networking, so an
# unset interface would make dnsmasq answer DHCP on *every* network the host
# is attached to — including the office LAN. Confining it is the whole point.
: "${INTERFACE:?Set INTERFACE to the provisioning NIC — DHCP/TFTP are confined to it}"

{
    echo "# Generated by entrypoint.sh"
    # DHCP/proxyDHCP + TFTP only — with host networking, dnsmasq would
    # otherwise also run a DNS server on the host's port 53 (and collide
    # with systemd-resolved or any local resolver).
    echo "port=0"
    echo "log-dhcp"
    echo "enable-tftp"
    echo "tftp-root=${TFTP_ROOT}"
    # interface + bind-interfaces: bind sockets to this NIC alone rather than
    # the wildcard address, so nothing leaks onto the host's other networks.
    echo "interface=${INTERFACE}"
    echo "bind-interfaces"
    echo "except-interface=lo"
    echo "no-hosts"
    echo "no-resolv"
    echo "dhcp-no-override"

    # Tag iPXE clients (they send DHCP option 175) and UEFI x86-64 clients.
    echo "dhcp-match=set:ipxe,175"
    echo "dhcp-match=set:efi64,option:client-arch,7"
    echo "dhcp-match=set:efi64,option:client-arch,9"

    if [ "$MODE" = "dhcp" ]; then
        : "${DHCP_RANGE_START:?Set DHCP_RANGE_START for MODE=dhcp}"
        : "${DHCP_RANGE_END:?Set DHCP_RANGE_END for MODE=dhcp}"
        echo "dhcp-authoritative"
        echo "dhcp-range=${DHCP_RANGE_START},${DHCP_RANGE_END},${DHCP_NETMASK:-255.255.255.0},${LEASE_TIME:-1h}"
        [ -n "${DHCP_ROUTER:-}" ] && echo "dhcp-option=3,${DHCP_ROUTER}"
        [ -n "${DHCP_DNS:-}" ] && echo "dhcp-option=6,${DHCP_DNS}"
        # Boot files by client type.
        echo "dhcp-boot=tag:ipxe,http://${SERVER_IP}/boot.ipxe"
        echo "dhcp-boot=tag:!ipxe,tag:efi64,ipxe.efi"
        echo "dhcp-boot=tag:!ipxe,tag:!efi64,undionly.kpxe"
    else
        : "${PROXY_SUBNET:?Set PROXY_SUBNET (e.g. 192.168.1.0) for MODE=proxy}"
        echo "dhcp-range=${PROXY_SUBNET},proxy"
        # proxyDHCP: hand PXE clients an iPXE binary, then iPXE fetches the script.
        echo "pxe-service=tag:!ipxe,x86PC,\"Network boot (BIOS)\",undionly.kpxe"
        echo "pxe-service=tag:!ipxe,BC_EFI,\"Network boot (UEFI)\",ipxe.efi"
        echo "pxe-service=tag:!ipxe,X86-64_EFI,\"Network boot (UEFI)\",ipxe.efi"
        echo "dhcp-boot=tag:ipxe,http://${SERVER_IP}/boot.ipxe"
    fi
} > "$CONF"

echo "----- dnsmasq configuration (MODE=$MODE) -----"
cat "$CONF"
echo "----------------------------------------------"

exec dnsmasq -k -d -C "$CONF"
